/** InnovTech design reminder: the about page communicates optimistic, accessible expertise without unverified claims. */
import { Link } from "wouter";
import { ArrowRight, Lightbulb, Network, Target } from "lucide-react";
import type { Lang } from "@/lib/site";

export default function About({ lang }: { lang: Lang }) {
  const t = lang === "fr";
  const values = [{ icon: Lightbulb, fr: "Innover avec intention", en: "Innovate with intent", textFr: "Nous choisissons des solutions qui servent un usage réel, pas la complexité pour elle-même.", textEn: "We choose solutions that serve a real use, not complexity for its own sake." }, { icon: Network, fr: "Rester connecté", en: "Stay connected", textFr: "La technologie est plus utile lorsqu’elle rapproche les personnes et les projets.", textEn: "Technology is more useful when it brings people and projects closer together." }, { icon: Target, fr: "Avancer clairement", en: "Move forward clearly", textFr: "Nous privilégions un accompagnement simple, direct et adapté à chaque besoin.", textEn: "We favour simple, direct support adapted to every need." }];
  return <main><section className="container grid gap-10 py-14 sm:py-20 lg:grid-cols-[1fr_0.9fr] lg:items-center"><div><p className="eyebrow">{t ? "À propos d’InnovTech" : "About InnovTech"}</p><h1 className="mt-3 max-w-3xl font-display text-4xl font-bold tracking-[-0.055em] text-[#081A3C] sm:text-6xl">{t ? "Innover, connecter, réussir." : "Innovate, connect, succeed."}</h1><p className="mt-6 max-w-2xl text-base leading-7 text-slate-600">{t ? "InnovTech réunit une sélection d’articles technologiques et des services de conception digitale dans une même expérience claire. Notre ambition : rendre la technologie plus accessible, plus utile et plus proche de vos projets." : "InnovTech brings together a selection of technology products and digital design services in one clear experience. Our ambition: make technology more accessible, useful and closer to your projects."}</p><Link href="/contact" className="mt-8 inline-flex items-center gap-2 text-sm font-extrabold text-blue-700 transition hover:gap-3">{t ? "Parlons de votre besoin" : "Let’s talk about your need"}<ArrowRight className="h-4 w-4" /></Link></div><div className="motion-card relative min-h-[300px] overflow-hidden rounded-[2rem] bg-[#EAF4FF] p-8"><div className="absolute inset-0 circuit-lines opacity-60" /><img src="/manus-storage/innovtech-symbol_33e7d57c.png" alt="" loading="lazy" decoding="async" className="relative mx-auto mt-3 h-56 w-56 object-contain drop-shadow-[0_18px_25px_rgba(18,103,243,0.23)]" /><p className="relative mx-auto mt-2 max-w-xs text-center font-display text-xl font-bold tracking-[-0.03em] text-[#081A3C]">{t ? "La technologie, avec un accompagnement humain." : "Technology, with human support."}</p></div></section><section className="bg-[#F4F8FF] py-14 sm:py-20"><div className="container grid gap-5 md:grid-cols-3">{values.map(({ icon: Icon, fr, en, textFr, textEn }) => <article key={fr} className="motion-card rounded-3xl bg-white p-7 shadow-[0_14px_32px_rgba(20,68,145,0.06)]"><Icon className="h-7 w-7 text-blue-700" /><h2 className="mt-6 font-display text-2xl font-bold tracking-[-0.035em] text-[#081A3C]">{t ? fr : en}</h2><p className="mt-3 text-sm leading-6 text-slate-600">{t ? textFr : textEn}</p></article>)}</div></section></main>;
}
