import { Link } from "wouter";
import { ArrowLeft, Cookie, FileCheck2, ShieldCheck, Store, UserRound } from "lucide-react";
import type { Lang } from "@/lib/site";

export type LegalPageKind = "privacy" | "legal-notice" | "terms" | "sales" | "cookies";

const details = { name: "InnovTech", phone: "+237 691 439 534", email: "evansabah2006@gmail.com", host: "Vercel Inc." };
const icons = { privacy: ShieldCheck, "legal-notice": UserRound, terms: FileCheck2, sales: Store, cookies: Cookie };

export default function Legal({ lang, kind }: { lang: Lang; kind: LegalPageKind }) {
  const t = lang === "fr";
  const title = { privacy: t ? "Politique de confidentialité" : "Privacy policy", "legal-notice": t ? "Mentions légales" : "Legal notice", terms: t ? "Conditions générales d’utilisation" : "Terms of use", sales: t ? "Conditions de vente" : "Terms of sale", cookies: t ? "Politique cookies" : "Cookie policy" }[kind];
  const Icon = icons[kind];
  const sections = kind === "privacy" ? [
    [t ? "Données concernées" : "Data concerned", t ? "InnovTech traite les informations que vous choisissez de transmettre : nom, besoin, créneau souhaité et contenu de votre message WhatsApp. Le site ne collecte pas de coordonnées bancaires et ne crée pas de compte client public." : "InnovTech processes the information you choose to provide: name, need, preferred time and WhatsApp message content. The site does not collect payment card details or create a public customer account."],
    [t ? "Finalités et base d’utilisation" : "Purposes and use", t ? "Ces données servent à répondre à votre demande, préparer un devis, confirmer une disponibilité ou organiser un rendez-vous. Le formulaire de rendez-vous prépare un message et vous redirige vers WhatsApp ; les données ne sont pas enregistrées dans le site par ce formulaire." : "This data is used to answer your request, prepare a quote, confirm availability or organise an appointment. The appointment form prepares a message and redirects you to WhatsApp; the form itself does not save this data in the website."],
    [t ? "Destinataires et conservation" : "Recipients and retention", t ? "Les échanges sont reçus par InnovTech via WhatsApp Business. Ils sont conservés seulement le temps utile au suivi de la demande et aux obligations applicables. La vidéo de démonstration est diffusée depuis une publication média GitHub ; elle ne vous inscrit à aucune liste marketing InnovTech." : "Messages are received by InnovTech through WhatsApp Business. They are kept only for the time needed to follow up the request and meet applicable obligations. The demonstration video is delivered from a GitHub media release; it does not subscribe you to any InnovTech marketing list."],
    [t ? "Vos droits et contact" : "Your rights and contact", t ? `Vous pouvez demander l’accès, la correction ou la suppression des informations vous concernant, ou vous opposer à certains usages, en écrivant à ${details.email} ou via WhatsApp au ${details.phone}.` : `You may request access, correction or deletion of your information, or object to certain uses, by writing to ${details.email} or using WhatsApp at ${details.phone}.`],
  ] : kind === "legal-notice" ? [
    [t ? "Éditeur" : "Publisher", `${details.name} — Cameroun. ${t ? "Contact" : "Contact"} : ${details.phone} · ${details.email}.`],
    [t ? "Informations à compléter" : "Information to complete", t ? "InnovTech est en cours de structuration. L’adresse professionnelle, la forme juridique, le numéro d’immatriculation et les identifiants fiscaux seront ajoutés dès leur obtention. Les clients ne doivent pas effectuer de paiement avant validation écrite des conditions applicables par InnovTech." : "InnovTech is being structured. Its business address, legal form, registration number and tax identifiers will be added once obtained. Customers should not make a payment before InnovTech confirms the applicable terms in writing."],
    [t ? "Hébergement" : "Hosting", `${t ? "Le site est déployé sur l’infrastructure de" : "The site is deployed on the infrastructure of"} ${details.host}.`],
    [t ? "Propriété intellectuelle" : "Intellectual property", t ? "Les textes, éléments graphiques et contenus InnovTech ne peuvent être reproduits sans autorisation. Les images et références fournisseurs restent soumises aux droits de leurs titulaires respectifs." : "InnovTech texts, graphics and content may not be reproduced without permission. Supplier images and references remain subject to their respective rightsholders."],
  ] : kind === "sales" ? [
    [t ? "Fonctionnement de la commande" : "How ordering works", t ? "La sélection d’un article et le bouton WhatsApp constituent une demande d’information ou de commande, pas une acceptation automatique. InnovTech confirme ensuite le modèle, le prix, la disponibilité et les éventuels frais." : "Selecting an item and using the WhatsApp button creates an information or order request, not an automatic acceptance. InnovTech then confirms the model, price, availability and any applicable fees."],
    [t ? "Paiement, livraison et retour" : "Payment, delivery and returns", t ? "Les moyens de paiement, la livraison, le délai, les conditions de retour ou de remboursement sont convenus par écrit avec le client avant tout paiement. Aucune carte bancaire ni paiement n’est traité sur ce site." : "Payment method, delivery, timing, return and refund terms are agreed in writing with the customer before any payment. No payment card or payment is processed on this website."],
    [t ? "Services numériques" : "Digital services", t ? "Le périmètre, le planning, le prix, les livrables et les modalités de maintenance d’un service digital font l’objet d’un devis ou d’un accord écrit avant démarrage." : "The scope, timeline, price, deliverables and maintenance terms for a digital service are set out in a quote or written agreement before work starts."],
  ] : kind === "cookies" ? [
    [t ? "Ce que le site utilise" : "What the site uses", t ? "InnovTech utilise un stockage local pour conserver votre choix de confidentialité et, si vous l’autorisez, vos préférences de langue et de thème. Ces éléments ne servent pas à la publicité personnalisée." : "InnovTech uses local storage to keep your privacy choice and, if you allow it, your language and theme preferences. These items are not used for personalised advertising."],
    [t ? "Mesure d’audience et marketing" : "Analytics and marketing", t ? "À ce jour, InnovTech n’active pas de cookie de marketing personnalisé ni de mesure d’audience optionnelle dans le parcours public. Votre choix est néanmoins conservé afin que tout futur outil optionnel respecte vos préférences avant activation." : "At this time, InnovTech does not enable personalised marketing cookies or optional analytics in the public journey. Your choice is still stored so that any future optional tool respects your preferences before activation."],
    [t ? "Modifier votre choix" : "Change your choice", t ? "Vous pouvez rouvrir les préférences à tout moment depuis le lien « Gérer mes cookies » dans le pied de page." : "You can reopen preferences at any time through the “Manage my cookies” link in the footer."],
  ] : [
    [t ? "Objet" : "Purpose", t ? "Ces conditions encadrent l’accès au site InnovTech et son utilisation. Elles ne remplacent pas les conditions spécifiques confirmées avec un client avant une commande ou une prestation." : "These terms govern access to and use of the InnovTech website. They do not replace the specific terms confirmed with a customer before an order or service."],
    [t ? "Utilisation du site" : "Use of the site", t ? "Les visiteurs doivent utiliser le site de manière licite, ne pas tenter d’en perturber le fonctionnement et fournir des informations exactes lorsqu’ils contactent InnovTech." : "Visitors must use the site lawfully, must not attempt to disrupt it and must provide accurate information when contacting InnovTech."],
    [t ? "Disponibilité et contenus" : "Availability and content", t ? "Les produits présentés sont proposés sous réserve de disponibilité. Les caractéristiques, photos, prix et modèles sont à confirmer avec InnovTech avant toute décision de paiement." : "Products are offered subject to availability. Specifications, photos, prices and models must be confirmed with InnovTech before any payment decision."],
  ];
  return <main className="legal-page bg-[#F4F8FF] py-10 dark:bg-[#081426] sm:py-16"><div className="container max-w-4xl"><Link href="/" className="inline-flex items-center gap-2 text-sm font-extrabold text-blue-700 dark:text-cyan-200"><ArrowLeft className="h-4 w-4" />{t ? "Retour à l’accueil" : "Back to home"}</Link><header className="mt-6 rounded-[2rem] bg-[#081A3C] p-7 text-white shadow-[0_22px_48px_rgba(8,26,60,0.18)] sm:p-10"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-cyan-300/15 text-cyan-200"><Icon className="h-6 w-6" /></span><p className="mt-6 text-xs font-extrabold uppercase tracking-[0.16em] text-cyan-300">InnovTech · Cameroun</p><h1 className="mt-3 font-display text-3xl font-bold tracking-[-0.05em] sm:text-5xl">{title}</h1><p className="mt-4 max-w-2xl text-sm leading-6 text-blue-100/80">{t ? "Dernière mise à jour : 26 août 2026. Ce document sera complété lorsque les informations d’immatriculation et d’adresse professionnelle d’InnovTech seront disponibles." : "Last updated: 26 August 2026. This document will be completed when InnovTech’s registration and business address details become available."}</p></header><div className="mt-6 grid gap-4">{sections.map(([heading, text]) => <section key={heading} className="rounded-3xl border border-blue-100 bg-white p-6 shadow-[0_12px_28px_rgba(20,68,145,0.06)] dark:border-blue-300/15 dark:bg-[#0d1f3a] sm:p-8"><h2 className="font-display text-2xl font-bold tracking-[-0.035em] text-[#081A3C] dark:text-white">{heading}</h2><p className="mt-3 text-sm leading-7 text-slate-600 dark:text-slate-300">{text}</p></section>)}</div></div></main>;
}
